version: '3.3'

# Use this file for an example for production

services:
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "8989:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    networks:
        - web
  phpmyadmin:
    image: nazarpc/phpmyadmin
    container_name: phpmyadmin
    restart: always
    stdin_open: true
    ports:
      - "8000:80"
    depends_on:
      - mysqldb
    volumes:
      - ./volumes/sessions:/sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    networks:
      - web
  itop:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      stdin_open: true
      environment:
        - ITOP_DB_HOST=mysql
        - ITOP_DB_NAME=itop
        - ITOP_DB_USER=itop
        - ITOP_DB_PASS=itop
        - ITOP_DB_CONNECTION=mysql
        - DB_CONNECTION=mysql
        - ITOP_DB_PORT=3306
        - DB_PORT=3306
        - PHP_TIMEZONE="America/Bogota"
        - PHP_ENABLE_UPLOADS="On"
        - PHP_MEMORY_LIMIT="256M"
        - PHP_POST_MAX_SIZE="10M"
        - PHP_UPLOAD_MAX_FILESIZE="8M"
        - PHP_MAX_FILE_UPLOADS="20"
        - PHP_MAX_INPUT_TIME="300"
        - PHP_LOG_ERRORS="On"
        - PHP_ERROR_REPORTING="E_ALL" # Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT
        - PMA_PORT=3306
      depends_on:
        - mysqldb
        - phpmyadmin
      ports:
        - "8080:80"
      volumes:
        - ./volumes/itop/config:/var/www/html/config
      networks:
        - web
networks:
  web:
    driver: bridge

